name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

  deploy:
    needs: build-and-push-ecr
    runs-on: self-hosted

    steps:
      - name: Pull Latest Image
        run: |
          docker pull \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Stop Existing Container
        run: |
          docker rm -f research-assistant || true

      - name: Run Container
        run: |
          docker run -d \
          --name research-assistant \
          -p 8501:8501 \
          -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
          -e TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }} \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest